### PR TITLE
Update to latest ctrulib

### PR DESCRIPTION
**Pull request by Substance12**
Travis passed the build, will try to build it myself later. 3DS, CIA and ELF builds were disabled but you can easily restore them. 

Besides that, all I did was updating xerpi's libraries and updating PTMU_GetBatteryChargeState and PTMU_GetBatteryLevel.

### CODE REVIEW

**Comment by Substance12** [comment]
Just built a .3dsx and tested it, seems to work perfectly. By the way, the .travis-deps.sh file seems to have outdated links to the libraries.

**Comment by Substance12** [comment]
I've also managed to get the battery function working (splitting it in one for the actual battery levels and another to check if it's charging or not), plus i've added a couple functions to check whether the console is a O3DS, O3DSXL, 2DS, N3DS or N3DSXL, the region and system language, but i'll wait until you accept this pull request and then create a new one.

**Comment by VideahGams** [comment]
@Substance12 the problem with splitting the battery function is Love does it in one function
https://love2d.org/wiki/love.system.getPowerInfo

**Comment by Substance12** [comment]
Oh, alright. I'll edit it to make it like that.

**Pull request merged**
