### PR TITLE
Create file.c

### PR DESCRIPTION
**Pull request by TurtleP**

### CODE REVIEW

**Comment by Substance12** [comment]
Holy crap let me make you a temple ;_;

**Comment by TurtleP** [comment]
Not sure why Travis just failed, but it doesn't have the OTHER files inside the framework yet :v. Nice work Videah.

**Comment by VideahGams** [comment]
It failed because you made a ton of small PR's instead of 1 big one ;P

**Comment by TurtleP** [comment]
WELP. GG me. I didn't know how to make one giant one. :v

**Comment by Substance12** [comment]
Why isn't this merged yet?

**Comment by TurtleP** [comment]
Because Videah has been busy. Also I still haven't got my temple :v

**Pull request closed without merging**
