### PR TITLE
Added source:Unload(), .gitignore.

### PR DESCRIPTION
**Pull request by Substance12**
source:Unload() is useful when you need to get rid of a big file (like BGMs) to free up memory. It also stops the audio before wiping it from memory. I haven't tested it with .raw files, but I guess it will only work on .wav files due to the 44 bytes less.

I'm not sure if it'll work if you put it on garbagecollect. It was my idea initially but I only got it to work if you unload it manually.

### CODE REVIEW

**Comment by Substance12** [comment]
Weird, Travis had an internal error. I can build without problems.

**Comment by VideahGams** [comment]
Wouldn't this be better using the garbage collector? I know you said you tried it, but did you try it like this?
```lua
alreadyLoadedMusic = nil
collectgarbage()
```
Also, one of the portlibs is giving a 500 error right now, which is why Travis is failing :v

**Comment by Substance12** [comment]
Yeah, I did try, didn't seem to work. I think it's because collectgarbage doesn't receive a "self" to point to the buffer? But i'll try again in a bit.

**Comment by Substance12** [comment]
Uh, weird, it works now. Pushing the changes now.

**Comment by Substance12** [comment]
And now it doesn't work anymore on my game. Damn.

**Comment by VideahGams** [comment]
@Substance12 Is it consistently working/not working, or does it happen randomly?

**Comment by Substance12** [comment]
Tweaked up the code (of my game, not of LÖVEPotion) a bit and now it just won't work at all :/

**Comment by VideahGams** [comment]
@Substance12 Hey, I just reworked love.audio with ctruLua's help, can you confirm if the problem still happens or no?

**Comment by Substance12** [comment]
Neat! I'll try it out now.

**Comment by Substance12** [comment]
Now I get very weird errors, in the top screen it just displays a console saying things like "LovePotion 1.0.7 BETA" and when I load a lot of PNGs it seems to give a libpng error and the top screen becomes corrupted

**Comment by VideahGams** [comment]
@Substance12 Oops, try now

**Comment by Substance12** [comment]
Now I get "Not enough linear memory available" but it's likely an issue with my code, i'll tweak it and see what happens

**Comment by Substance12** [comment]
I managed to fix it, thanks! Just one thing: all sounds seem to be set up to loop as default.

**Comment by VideahGams** [comment]
@Substance12 Yeah, I noticed that last night but had to pass out on my bed because I was so tired, I'll fix it today :P

**Comment by Substance12** [comment]
Ok, no hurry.

**Comment by Substance12** [comment]
I guess this pull request can be closed now? At least add the .gitignore so people can build directly from a cloned repo :P

**Comment by VideahGams** [comment]
Done :D

**Pull request closed without merging**
