### PR TITLE
Update main.c

### PR DESCRIPTION
**Pull request by s3r1alpari4h**
Colored errors are just awesome.

### CODE REVIEW

**Comment by s3r1alpari4h** [comment]
Wtf?

**Comment by VideahGams** [comment]
The reason the PR failed checks is because of the ctrulib rewrite that I need to update LovePotion to use

**Comment by s3r1alpari4h** [comment]
Ah okay

**Comment by Substance12** [comment]
ctrulib got rewritten? When?

**Comment by VideahGams** [comment]
@Substance12 [Since 3 weeks ago](https://github.com/smealum/ctrulib/commit/d4a24169c5091f48a6dd7a2359dcbdac0afceea6)

**Pull request merged**
