### PR TITLE
Update system.c

### PR DESCRIPTION
**Pull request by Substance12**
Edited love.system.getPowerInfo (seems to work fine now), and added
love.system.getModel, love.system.getRegion and love.system.getLanguage. Also fixed sfilib and sftdlib, now they don't need sf2d.h in their respective include folders.

About the new functions, I didn't knew where to put them but love.system seemed the most fitting. Change it if you feel like it fits better somewhere else.

### CODE REVIEW

**Comment by VideahGams** [comment]
[Travis is failing to build this PR](https://travis-ci.org/VideahGams/LovePotion/builds/98586848), if you can fix it, I'll merge (thanks for the help btw :+1:)

**Comment by Substance12** [comment]
Yes, it's just I forgot to update the sf2d.h location of some files. Just pushed a commit that should be enough.

And thank YOU for the port, it's helped me a lot :D

**Comment by Substance12** [comment]
I have a lot of free time now so i'll see what else I can do with the code.

By the way, I forgot to tell you that I managed to compile under Windows. I've used the makefile below for portlibs:

https://github.com/cpp3ds/3ds_portlibs

All worked except for freetype. I had to install gcc with MingW32 and install zlib (NOT the portlib).

What didn't work was .cia and .3ds compiling. I don't know what the issue is, but it's related to makerom. It didn't work on Windows, and when I tried to pass a build with Travis it gave another makerom error about corrupted memory, so I just decided to delete the outputs in the makefile. Pretty sure it's not just a Windows issue.

**Comment by VideahGams** [comment]
I'm probably going to remove .cia and .3ds support anyways, I never got round to making it work and I don't know if its actually possible to get working. 

It's good that you got it building on Windows, I wasn't sure if that was possible!

**Pull request merged**
